version: '3'

volumes:
  pg_volume:
  redis-data:

services:
  pg:
    image: postgres:14-alpine3.17
    ports: 
      - "${PG_PORT}:5432"
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    volumes:
      - pg_volume:/var/lib/postgresql/data

  redis:
    image: redis:7.2.5-alpine3.20
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  migrator:
    build: 
      context: .
      dockerfile: migrations.Dockerfile
    restart: on-failure
    environment:
      - DB_HOST=pg